#default server port - dev
server:
    port: 8080

#environment enablement [dev, prod]
spring:
    profiles:
        active: prod

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
